# Runs internal automation for pull requests

name: "Add labels to github PRs based on context"
on:
  pull_request:

jobs:
  shared-pr-labeller:
    name: "Add Labels to PRs.  Safe to Merge on fail"
    runs-on: ubuntu-latest
    steps:
      - name: Run Issue Command from workflow-actions
        run: |
          echo "{{github.actor}}"
        
